2022-07-19 11:06:45.299863 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:06:49.673323 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"The first screen has a spinning\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following UnsupportedError was thrown running a test:\\nUnsupported operation: Platform._operatingSystem\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49     throw_\\ndart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 244:5                  _operatingSystem\\ndart-sdk/lib/io/platform_impl.dart 56:40                                         get operatingSystem\\ndart-sdk/lib/io/platform.dart 64:45                                              get _operatingSystem\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 839:8  get\\ndart-sdk/lib/io/platform.dart 145:51                                             get isWindows\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 839:8  get\\npackages/fe_ezlang_flashcard/main.dart 27:16                                     main$\\napp_test.dart 12:11                                                              <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54               runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5               _async\\napp_test.dart 11:53                                                              <fn>\\npackages/flutter_test/src/widget_tester.dart 170:29                              <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50               <fn>\\ndart-sdk/lib/async/zone.dart 1434:47                                             _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                             runUnary\\ndart-sdk/lib/async/future_impl.dart 147:18                                       handleValue\\ndart-sdk/lib/async/future_impl.dart 766:44                                       handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 795:13                                       _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 566:5                                        [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 639:7                                        <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                             _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                             run\\ndart-sdk/lib/async/zone.dart 1236:7                                              runGuarded\\ndart-sdk/lib/async/zone.dart 1276:23                                             callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                                 _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                                  _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15              <fn>\\n\\nThe test description was:\\n  The first screen has a spinning\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-19 11:08:18.164475 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:10:33.209700 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:10:45.794198 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"The first screen has a spinning\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following TestFailure was thrown running a test:\\nExpected: exactly one matching node in the widget tree\\n  Actual: _WidgetTypeFinder:<zero widgets with type\\n\\\"CircularProgressIndicator\\\" (ignoring offstage widgets)>\\n   Which: means none were found but one was expected\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\npackages/test_api/src/expect/expect.dart 137:31                               fail\\npackages/test_api/src/expect/expect.dart 132:3                                _expect\\npackages/test_api/src/expect/expect.dart 46:3                                 expect$\\npackages/flutter_test/src/widget_tester.dart 455:16                           expect$\\napp_test.dart 17:7                                                            <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>\\ndart-sdk/lib/async/zone.dart 1434:47                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/future_impl.dart 147:18                                    handleValue\\ndart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 639:7                                     <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\ndart-sdk/lib/async/zone.dart 1236:7                                           runGuarded\\ndart-sdk/lib/async/zone.dart 1276:23                                          callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>\\n\\nThe test description was:\\n  The first screen has a spinning\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-19 11:11:31.388193 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:14:52.862737 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:14:56.968829 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"The first screen has a spinning\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following TestFailure was thrown running a test:\\nExpected: exactly one matching node in the widget tree\\n  Actual: _WidgetTypeFinder:<zero widgets with type\\n\\\"CircularProgressIndicator\\\" (ignoring offstage widgets)>\\n   Which: means none were found but one was expected\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\npackages/test_api/src/expect/expect.dart 137:31                               fail\\npackages/test_api/src/expect/expect.dart 132:3                                _expect\\npackages/test_api/src/expect/expect.dart 46:3                                 expect$\\npackages/flutter_test/src/widget_tester.dart 455:16                           expect$\\napp_test.dart 19:7                                                            <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>\\ndart-sdk/lib/async/zone.dart 1434:47                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/future_impl.dart 147:18                                    handleValue\\ndart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 639:7                                     <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\ndart-sdk/lib/async/zone.dart 1236:7                                           runGuarded\\ndart-sdk/lib/async/zone.dart 1276:23                                          callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>\\n\\nThe test description was:\\n  The first screen has a spinning\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-19 11:16:11.895569 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:16:17.696312 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"The first screen has a spinning\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following TestFailure was thrown running a test:\\nExpected: exactly one matching node in the widget tree\\n  Actual: _WidgetTypeFinder:<zero widgets with type\\n\\\"CircularProgressIndicator\\\" (ignoring offstage widgets)>\\n   Which: means none were found but one was expected\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\npackages/test_api/src/expect/expect.dart 137:31                               fail\\npackages/test_api/src/expect/expect.dart 132:3                                _expect\\npackages/test_api/src/expect/expect.dart 46:3                                 expect$\\npackages/flutter_test/src/widget_tester.dart 455:16                           expect$\\napp_test.dart 18:7                                                            <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>\\ndart-sdk/lib/async/zone.dart 1434:47                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/future_impl.dart 147:18                                    handleValue\\ndart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 639:7                                     <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\ndart-sdk/lib/async/zone.dart 1236:7                                           runGuarded\\ndart-sdk/lib/async/zone.dart 1276:23                                          callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>\\n\\nThe test description was:\\n  The first screen has a spinning\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-19 11:18:10.717740 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:18:20.847379 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"The first screen has a spinning\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following TestFailure was thrown running a test:\\nExpected: exactly one matching node in the widget tree\\n  Actual: _WidgetTypeFinder:<8 widgets with type \\\"Text\\\" (ignoring\\noffstage widgets): Text(\\\"Hey There,\\\", inherit: true, size: 20.0,\\ndependencies: [DefaultTextStyle, MediaQuery]), Text(\\\"Welcome\\nBack\\\", inherit: true, size: 30.0, weight: 700, dependencies:\\n[DefaultTextStyle, MediaQuery]), Text(\\\"Email\\\", debugLabel:\\n((((englishLike titleMedium 2014).merge((whiteRedwoodCity\\ntitleMedium).merge(((whiteRedwoodCity\\ntitleMedium).copyWith).copyWith))).merge(unknown)).merge(unknown)).merge(unknown),\\ninherit: false, color: Color(0xffada4a5), family:\\nPoppins_regular, familyFallback: [Poppins], size: 16.0, weight:\\n400, baseline: alphabetic, decoration: TextDecoration.none,\\ntextAlign: start, overflow: ellipsis, maxLines: 1, dependencies:\\n[DefaultTextStyle, MediaQuery]), ...>\\n   Which: is too many\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\npackages/test_api/src/expect/expect.dart 137:31                               fail\\npackages/test_api/src/expect/expect.dart 132:3                                _expect\\npackages/test_api/src/expect/expect.dart 46:3                                 expect$\\npackages/flutter_test/src/widget_tester.dart 455:16                           expect$\\napp_test.dart 18:7                                                            <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>\\ndart-sdk/lib/async/zone.dart 1434:47                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/future_impl.dart 147:18                                    handleValue\\ndart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 639:7                                     <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\ndart-sdk/lib/async/zone.dart 1236:7                                           runGuarded\\ndart-sdk/lib/async/zone.dart 1276:23                                          callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>\\n\\nThe test description was:\\n  The first screen has a spinning\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-19 11:19:50.914623 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:32:49.812347 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:33:00.130668 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}}
2022-07-19 11:37:12.541043 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:37:22.147815 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid Credential\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following StateError was thrown running a test:\\nBad state: No element\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/core/iterable.dart 654:63                                        get single\\npackages/flutter_test/src/controller.dart 156:30                              state\\npackages/flutter_test/src/widget_tester.dart 1042:42                          <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1041:39                          <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\npackages/flutter_test/src/test_async_utils.dart 71:35                         guard\\npackages/flutter_test/src/widget_tester.dart 1041:27                          showKeyboard\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1040:28                          showKeyboard\\npackages/flutter_test/src/widget_tester.dart 1077:13                          <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1076:39                          <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\npackages/flutter_test/src/test_async_utils.dart 71:35                         guard\\npackages/flutter_test/src/widget_tester.dart 1076:27                          enterText\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1075:25                          enterText\\napp_test.dart 22:21                                                           <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>\\ndart-sdk/lib/async/zone.dart 1434:47                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/future_impl.dart 147:18                                    handleValue\\ndart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 639:7                                     <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\ndart-sdk/lib/async/zone.dart 1236:7                                           runGuarded\\ndart-sdk/lib/async/zone.dart 1276:23                                          callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>\\n\\nThe test description was:\\n  Invalid Credential\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-19 11:39:27.828551 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:40:43.249529 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:40:53.314646 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid Credential\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following StateError was thrown running a test:\\nBad state: No element\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/core/iterable.dart 654:63                                        get single\\npackages/flutter_test/src/controller.dart 156:30                              state\\npackages/flutter_test/src/widget_tester.dart 1042:42                          <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1041:39                          <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\npackages/flutter_test/src/test_async_utils.dart 71:35                         guard\\npackages/flutter_test/src/widget_tester.dart 1041:27                          showKeyboard\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1040:28                          showKeyboard\\npackages/flutter_test/src/widget_tester.dart 1077:13                          <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1076:39                          <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\npackages/flutter_test/src/test_async_utils.dart 71:35                         guard\\npackages/flutter_test/src/widget_tester.dart 1076:27                          enterText\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1075:25                          enterText\\napp_test.dart 22:21                                                           <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>\\ndart-sdk/lib/async/zone.dart 1434:47                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/future_impl.dart 147:18                                    handleValue\\ndart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 639:7                                     <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\ndart-sdk/lib/async/zone.dart 1236:7                                           runGuarded\\ndart-sdk/lib/async/zone.dart 1276:23                                          callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>\\n\\nThe test description was:\\n  Invalid Credential\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-19 11:41:56.550502 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:42:07.254300 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}}
2022-07-19 11:44:27.468164 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:44:33.922632 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}}
2022-07-19 11:45:44.338551 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:45:55.346467 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid Credential\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following StateError was thrown running a test:\\nBad state: Too many elements\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/core/iterable.dart 656:60                                        get single\\npackages/flutter_test/src/controller.dart 156:30                              state\\npackages/flutter_test/src/widget_tester.dart 1042:42                          <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1041:39                          <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\npackages/flutter_test/src/test_async_utils.dart 71:35                         guard\\npackages/flutter_test/src/widget_tester.dart 1041:27                          showKeyboard\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1040:28                          showKeyboard\\npackages/flutter_test/src/widget_tester.dart 1077:13                          <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1076:39                          <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\npackages/flutter_test/src/test_async_utils.dart 71:35                         guard\\npackages/flutter_test/src/widget_tester.dart 1076:27                          enterText\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async\\npackages/flutter_test/src/widget_tester.dart 1075:25                          enterText\\napp_test.dart 32:21                                                           <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>\\ndart-sdk/lib/async/zone.dart 1434:47                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/future_impl.dart 147:18                                    handleValue\\ndart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 639:7                                     <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\ndart-sdk/lib/async/zone.dart 1236:7                                           runGuarded\\ndart-sdk/lib/async/zone.dart 1276:23                                          callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>\\n\\nThe test description was:\\n  Invalid Credential\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-19 11:47:21.624901 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:47:35.287747 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid Credential\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following TestFailure was thrown running a test:\\nExpected: at least one matching node in the widget tree\\n  Actual: _TextFinder:<zero widgets with text \\\"invalid\\\" (ignoring\\noffstage widgets)>\\n   Which: means none were found but some were expected\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\npackages/test_api/src/expect/expect.dart 137:31                               fail\\npackages/test_api/src/expect/expect.dart 132:3                                _expect\\npackages/test_api/src/expect/expect.dart 46:3                                 expect$\\npackages/flutter_test/src/widget_tester.dart 455:16                           expect$\\napp_test.dart 28:9                                                            <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>\\ndart-sdk/lib/async/zone.dart 1434:47                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/future_impl.dart 147:18                                    handleValue\\ndart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 639:7                                     <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\ndart-sdk/lib/async/zone.dart 1236:7                                           runGuarded\\ndart-sdk/lib/async/zone.dart 1276:23                                          callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>\\n\\nThe test description was:\\n  Invalid Credential\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-19 11:48:20.655593 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:48:31.560759 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid Credential\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following TestFailure was thrown running a test:\\nExpected: at least one matching node in the widget tree\\n  Actual: _TextFinder:<zero widgets with text \\\"invalid\\\" (ignoring\\noffstage widgets)>\\n   Which: means none were found but some were expected\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\npackages/test_api/src/expect/expect.dart 137:31                               fail\\npackages/test_api/src/expect/expect.dart 132:3                                _expect\\npackages/test_api/src/expect/expect.dart 46:3                                 expect$\\npackages/flutter_test/src/widget_tester.dart 455:16                           expect$\\napp_test.dart 30:9                                                            <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>\\ndart-sdk/lib/async/zone.dart 1434:47                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/future_impl.dart 147:18                                    handleValue\\ndart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 639:7                                     <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\ndart-sdk/lib/async/zone.dart 1236:7                                           runGuarded\\ndart-sdk/lib/async/zone.dart 1276:23                                          callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>\\n\\nThe test description was:\\n  Invalid Credential\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-19 11:49:47.590400 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:50:01.287050 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid Credential\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following TestFailure was thrown running a test:\\nExpected: at least one matching node in the widget tree\\n  Actual: _TextFinder:<zero widgets with text \\\"Invalid email\\\"\\n(ignoring offstage widgets)>\\n   Which: means none were found but some were expected\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\npackages/test_api/src/expect/expect.dart 137:31                               fail\\npackages/test_api/src/expect/expect.dart 132:3                                _expect\\npackages/test_api/src/expect/expect.dart 46:3                                 expect$\\npackages/flutter_test/src/widget_tester.dart 455:16                           expect$\\napp_test.dart 30:9                                                            <fn>\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>\\ndart-sdk/lib/async/zone.dart 1434:47                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/future_impl.dart 147:18                                    handleValue\\ndart-sdk/lib/async/future_impl.dart 766:44                                    handleValueCallback\\ndart-sdk/lib/async/future_impl.dart 795:13                                    _propagateToListeners\\ndart-sdk/lib/async/future_impl.dart 566:5                                     [_completeWithValue]\\ndart-sdk/lib/async/future_impl.dart 639:7                                     <fn>\\ndart-sdk/lib/async/zone.dart 1426:13                                          _rootRun\\ndart-sdk/lib/async/zone.dart 1328:19                                          run\\ndart-sdk/lib/async/zone.dart 1236:7                                           runGuarded\\ndart-sdk/lib/async/zone.dart 1276:23                                          callback\\ndart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop\\ndart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop\\ndart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>\\n\\nThe test description was:\\n  Invalid Credential\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-19 11:50:52.577592 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:51:01.615377 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}}
2022-07-19 11:57:50.393926 >>> {command: request_data, timeout: 1200000}
2022-07-19 11:57:55.493547 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid Credential\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following message was thrown:\\nMultiple exceptions (2) were detected during the running of the\\ncurrent test, and at least one was unexpected.\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 14:07:44.013123 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:07:47.215328 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}}
2022-07-20 14:08:54.733027 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:08:57.952728 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}}
2022-07-20 14:17:33.280807 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:17:37.230728 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}}
2022-07-20 14:22:30.258812 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:22:33.785822 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}}
2022-07-20 14:23:18.560627 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:23:23.208455 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 14:26:45.249116 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:26:49.657466 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following message was thrown:\\nMultiple exceptions (2) were detected during the running of the\\ncurrent test, and at least one was unexpected.\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 14:29:53.905709 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:29:57.998057 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following message was thrown:\\nMultiple exceptions (2) were detected during the running of the\\ncurrent test, and at least one was unexpected.\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 14:31:20.316982 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:31:24.814417 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following message was thrown:\\nMultiple exceptions (2) were detected during the running of the\\ncurrent test, and at least one was unexpected.\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 14:45:59.669583 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:46:04.287821 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════\\nThe following message was thrown:\\nMultiple exceptions (2) were detected during the running of the\\ncurrent test, and at least one was unexpected.\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 14:49:18.820613 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:49:23.205565 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 14:51:46.965925 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:51:51.331480 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 14:53:11.987614 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:53:16.087793 <<< {isError: false, response: {message: {"result":"true","failureDetails":[]}}}
2022-07-20 14:54:02.093747 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:54:06.647189 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 14:55:26.324042 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:55:35.384318 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 14:57:52.440796 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:57:58.326314 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 14:59:23.188787 >>> {command: request_data, timeout: 1200000}
2022-07-20 14:59:29.155128 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 15:02:05.882752 >>> {command: request_data, timeout: 1200000}
2022-07-20 15:02:11.672616 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 15:05:05.639854 >>> {command: request_data, timeout: 1200000}
2022-07-20 15:05:11.197867 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 15:08:33.364122 >>> {command: request_data, timeout: 1200000}
2022-07-20 15:08:39.238498 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 15:10:50.036808 >>> {command: request_data, timeout: 1200000}
2022-07-20 15:10:54.795151 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 15:11:44.728933 >>> {command: request_data, timeout: 1200000}
2022-07-20 15:11:49.792936 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
2022-07-20 15:13:03.719879 >>> {command: request_data, timeout: 1200000}
2022-07-20 15:13:09.085157 <<< {isError: false, response: {message: {"result":"false","failureDetails":["{\"methodName\":\"Invalid input\",\"details\":\"══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞══════════════════════\\nThe following assertion was thrown during a scheduler callback:\\nAssertion failed:\\nfile:///Users/phuc.tran/Development/flutter/packages/flutter/lib/src/semantics/semantics.dart:3014:16\\nnode.parent == null || !node.parent!.isPartOfNodeMerging ||\\nnode.isMergedIntoParent\\nis not true\\n\\nWhen the exception was thrown, this was the stack:\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_\\ndart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed\\npackages/flutter/src/semantics/semantics.dart 3014:80                         sendSemanticsUpdate\\npackages/flutter/src/rendering/object.dart 1098:7                             flushSemantics\\npackages/flutter/src/rendering/binding.dart 509:21                            drawFrame\\npackages/flutter/src/widgets/binding.dart 892:13                              drawFrame\\npackages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]\\npackages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame\\npackages/flutter_test/src/binding.dart 1546:30                                handleDrawFrame\\npackages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]\\nlib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke\\nlib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame\\nlib/_engine/engine/initialization.dart 194:45                                 <fn>\\ndart-sdk/lib/async/zone.dart 1442:13                                          _rootRunUnary\\ndart-sdk/lib/async/zone.dart 1335:19                                          runUnary\\ndart-sdk/lib/async/zone.dart 1244:7                                           runUnaryGuarded\\ndart-sdk/lib/async/zone.dart 1281:26                                          <fn>\\n═════════════════════════════════════════════════════════════════\\n\"}"]}}}
